obj-m := pcd_n.o

ARCH=arm
CROSS_COMPILE=arm-none-linux-gnueabihf-
KERN_DIR=/home/rushikesh/workspace/ldd/source/linux/
HOST_KERN_DIR = /lib/modules/$(shell uname -r)/build/

all:
	make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KERN_DIR)  M=$(PWD) modules
clean:
	make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KERN_DIR)  M=$(PWD) clean
help:
	make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KERN_DIR)  M=$(PWD) help

host:
	make -C $(HOST_KERN_DIR) M=$(PWD) modules
